### PR TITLE
Fix autostart

### LINKED ISSUE #39: Frama-C plugin shall not be run if not requested
Even if no C code is present Frama-C plugin execute itself during sonar-scanner call.

I would like to the plugin execute only when we analyze C code (or C++) or when plugin's property is set.

None for now

None

### PR DESCRIPTION
**Pull request by ThomasCluzel**
## Proposed changes

> _Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue._

The Frama-C Sensor is currently executed by the sonar-scanner on every project. This PR fixes this behavior by restricting the Frama-C Sensor to C and C++ projects only.

## Types of changes

What types of changes does your code introduce to this plugin?
> _Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

> _List here all issues closed by your changes. Use a list of items like `- [x] Close #0`_

- [x] Close #39 

## Checklist

> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/lequal/sonar-frama-c-plugin/blob/master/CONTRIBUTING.md) doc
- [ ] I agree with the [CODE OF CONDUCT](https://github.com/lequal/sonar-frama-c-plugin/blob/master/CONTRIBUTING.md)
- [ ] Lint and unit tests pass locally with my changes
- [ ] SonarCloud and Travis CI tests pass with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

> _If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc..._

### CODE REVIEW

**Comment by ThomasCluzel** [comment]
With these modifications, the sensor is no longer launched on every code analysis but only on C/C++ projects.
However, in order the sonar-scanner to know that the project contains C/C++ code, either the official C/C++ SonarQube plugin or the C++ (Community) plugin must be installed along with the Frama-C plugin.

**Comment by Sancretor** [comment]
Is this PR also fixing #37 ?

**Comment by ThomasCluzel** [comment]
@Sancretor Well, yes and no.
It is now related to C languages defined by CFamily or sonar-cxx and needs at least one of these plugins to be used but it still defines its own language and repository of rules. It is a static and implicit dependence not a dynamically declared one.
However, if everyone agrees that it is enough to fix #37 then yes.

**Comment by Sancretor** [comment]
@ThomasCluzel Thanks for the answer.
Then I suppose it does not totally fix this issue, at most partially...
Ok, I'll merge the PR.

**Pull request merged**
